apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: debian
    command: ["printenv"]
    args: ["HOSTNAME","KUBERNATES_PORT"]
  restartPolicy: OnFailure
